cloudfoundry/capi-release

- jobs/blobstore/spec
- jobs/blobstore/templates/bpm.yml.erb
- jobs/blobstore/templates/bpm/nginx.yml.erb
- jobs/blobstore/templates/bpm/url_signer.yml.erb
- jobs/cc_uploader/spec
- jobs/cc_uploader/templates/bpm.yml.erb
- jobs/cc_uploader/templates/bpm/cc_uploader.yml.erb
- jobs/nsync/spec
- jobs/nsync/templates/bpm.yml.erb
- jobs/nsync/templates/bpm/bulker.yml.erb
- jobs/nsync/templates/bpm/listener.yml.erb
- jobs/stager/spec
- jobs/stager/templates/bpm.yml.erb
- jobs/stager/templates/bpm/stager.yml.erb
- jobs/tps/spec
- jobs/tps/templates/bpm.yml.erb
- jobs/tps/templates/bpm/listener.yml.erb
- jobs/tps/templates/bpm/watcher.yml.erb
[#150721952]
Signed-off-by: Anoop Gopalakrishnan <agopalakrishnan@pivotal.io>
> Convert BPM configuration to single file

- jobs/blobstore/spec
- jobs/blobstore/templates/backup
- jobs/blobstore/templates/restore
[#151209989]
cc: @ChunyiLyu
PR for backup and restore scripts for the blobstore as discussed in the context of #149590309
> Added bbr scripts for the blobstore

- jobs/cloud_controller_clock/spec
- jobs/cloud_controller_ng/spec
- jobs/cloud_controller_worker/spec
- jobs/nsync/spec
- jobs/stager/spec
Signed-off-by: Dave Goddard <dave@goddard.id.au>
> Add cflinuxfs3 to lifecycle bundles [#142068573]

- jobs/cloud_controller_clock/spec
- jobs/cloud_controller_ng/spec
- jobs/cloud_controller_worker/spec
> Update 'stacks' property description in the cloud_controller_ng spec

- jobs/cc_deployment_updater/spec
- jobs/cloud_controller_clock/spec
- jobs/cloud_controller_ng/spec
- jobs/cloud_controller_worker/spec
Reverts cloudfoundry/capi-release#151
> Revert "Remove support for the "windows2016" stack"

- jobs/cc_deployment_updater/spec
- jobs/cc_route_syncer/spec
- jobs/cc_uploader/templates/cc_uploader_ctl.erb
- jobs/cloud_controller_clock/spec
- jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
- jobs/cloud_controller_ng/spec
- jobs/cloud_controller_ng/templates/post-start.sh.erb
- jobs/cloud_controller_ng/templates/pre-start.sh.erb
- jobs/cloud_controller_worker/spec
- jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
- shared_job_templates/blobstore_waiter.sh.erb
Just some grammar corrections for descriptions, log and other messages
> Some typos corrected

- packages/cloud_controller_ng/spec
- Corresponding CC commit: https://github.com/cloudfoundry/cloud_controller_ng/commit/514e924b9bec86e901592b29e9f0d7e804524cce
- Corresponding CC PR: https://github.com/cloudfoundry/cloud_controller_ng/pull/1711
> Remove vendor directory from packaging script

- config/blobs.yml
- packages/nginx/README.md
- packages/nginx/packaging
- packages/nginx/spec
- packages/nginx_webdav/packaging
- packages/nginx_webdav/spec
Co-authored-by: Jenna Goldstrich <jgoldstrich@pivotal.io>
Co-authored-by: Marc Paquette <mpaquette@vmware.com>
Deployed this to a bosh-lite and ran CATS, everything seems to be working
> Updated nginx to 1.20.1 and uploaded it to capi-release blobstore

- .github/workflows/unit_tests.yml
- runs on prs and develop branch
Authored-by: Michael Oleske <moleske@pivotal.io>
> Enable github actions for config_template_tests

- docs/releasing-capi.md
> Add note about checking API version numbers

- packages/nginx_webdav/README.md
> Fix markdown table

- packages/blobstore_url_signer/packaging
- packages/cc_uploader/packaging
- packages/tps/packaging
> Disable VCS stamping when packaging golang dependencies

- config/blobs.yml
- packages/nginx/README.md
- packages/nginx/packaging
- packages/nginx/spec
- packages/nginx_webdav/packaging
- packages/nginx_webdav/spec
We'd like to update pcre from 8.42 to 8.45.
> Update nginx/pcre to 8.45

- config/blobs.yml
- jobs/nfs_mounter/templates/pre-start.sh.erb
- packages/nfs-debs/README.md
- packages/nfs-debs/spec
Authored-by: Seth Boyles <sboyles@pivotal.io>
> Bump nfs_mounter deps for jammy stemcell

- packages/nfs-debs/spec
Co-authored-by: Seth Boyles <sboyles@pivotal.io>
Co-authored-by: David Alvarado <alvaradoda@vmware.com>
> nfs-deps should have been nfs-debs

- jobs/cloud_controller_ng/spec
- jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
> Puma thin refactor

- jobs/cloud_controller_worker/spec
- jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
Authored-by: Seth Boyles <sboyles@pivotal.io>
> Timeout for async service bindings in manifests

- config/blobs.yml
- packages/libpq/README.md
- packages/libpq/packaging
- packages/libpq/spec
> Bump libpq to postgres 11.18

- jobs/cloud_controller_clock/spec
- jobs/cloud_controller_ng/spec
> Improve spec clarity

- jobs/cc_deployment_updater/spec
- jobs/rotate_cc_database_key/spec
> Remove 'experimental' from job descriptions

- jobs/cloud_controller_ng/spec
- jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
- jobs/cloud_controller_worker/spec
- jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
- spec/cloud_controller_ng/cloud_controller_ng_spec.rb
- spec/cloud_controller_worker/cloud_controller_worker_spec.rb
Add config required by https://github.com/cloudfoundry/cloud_controller_ng/pull/3209.
> Add broker_client_response_parser logging config

- jobs/cloud_controller_ng/spec
- jobs/cloud_controller_worker/spec
> Adapt description of the log_response_fields configuration

- jobs/rotate_cc_database_key/spec
- jobs/rotate_cc_database_key/templates/cloud_controller_ng.yml.erb
- spec/rotate_cc_database_key/rotate_cc_database_key_spec.rb
ccng: https://github.com/cloudfoundry/cloud_controller_ng/pull/3283
> Make cc parameter `stdout_sink_enabled` configurable

- config/blobs.yml
- packages/libpq/README.md
- packages/libpq/packaging
- packages/libpq/spec
> Bump postgres to v11.22

- jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
- spec/cloud_controller_ng/cloud_controller_ng_spec.rb
> Fix legacy_md5_buildpack_paths_enabled param

- README.md
- docs/fix-commit-to-main.md
- docs/releasing-capi.md
> Switch to new CI

- jobs/redis/spec
> Fix dummy redis job

- spec/.rubocop.yml
> Add new rubocop

- docs/releasing-capi.md
> Add note to run job to publish v3 docs

- config/blobs.yml
Add new pcre2 version 10.44 to blobs.yml
#455
> add new pcre to blobs.yml

- jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
> Add missing template for app_instance_stopping_state

- docs/releasing-capi.md
Remove unnecessary step
Prevent doing unnecessary step
> No fanout tests any more

- spec/.rubocop.yml
> Add new cops that weren't configured

- jobs/cloud_controller_ng/spec
- jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
- jobs/cloud_controller_worker/spec
- jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
- spec/cloud_controller_ng/cloud_controller_ng_spec.rb
- spec/cloud_controller_worker/cloud_controller_worker_spec.rb
Add config for max poll interval
https://github.com/cloudfoundry/cloud_controller_ng/pull/4328
> Add config for max poll interval
