cloudfoundry/capi-release

jobs/cloud_controller_clock/spec
jobs/cloud_controller_ng/spec
jobs/cloud_controller_worker/spec

Adds 'hm9000.port' to the specs for use in determining the correct internal address (separate PR for changes to cloud_controller_ng)
[#118507195]
Signed-off-by: Swetha Repakula <srepaku@us.ibm.com>

Add hm9000.port to cloud_controller_ng/clock/worker spec

---

jobs/cloud_controller_ng/spec

Expose the minimum_candidate_stagers config property in the CC spec
[#119362989]
Signed-off-by: Swetha Repakula <srepaku@us.ibm.com>

Add minimum candidate stagers to CC spec

---

packages/ruby-2.3/packaging

The bundler dependency should never have to come from rubygems.org, it should be available locally from blobs binaries upon compilation. This hasn't been an issue for CC specifically but it has been for other CF ruby components, see https://github.com/cloudfoundry/cf-release/pull/963 for reference.
If an environment where I'm installing CF is not completely firewalled off from the internet, the compiler could in some situations believe that requests to rubygems.org are allowed, but not be able to download the necessary dependency. This prevents this from ever …

specify local to install bundler

---

jobs/blobstore/templates/blobstore.conf.erb

Sets the port of the default blobstore nginx server to `blobstore.port`
The blobstore conflicts with gorouter when colocated. This allows us to run them on separate ports.
* So that it doesn't conflict with gorouter
Signed-off-by: Anthony Emengo <aemengo@pivotal.io>

Make blobstore default nginx configurable

---

PULL_REQUEST_TEMPLATE.md

Change PR template to reflect current practices in the Capi team.
Less comments in future PRs.
_No. Made against `develop` :-)_
_Not necessary._

Require to make PRs against develop, not master

---

.gitmodules

Fixed the submodule URL for the YAML go package
Git was complaining when syncing the submodule with trailing slash in the URL
Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>

Fixed the YAML submodule URL

---

src/capi_utils/container_utils.sh

This change allows jobs to run correctly in garden-runc containers as well as in the previously supported garden-linux and docker containers.
See also https://github.com/cloudfoundry/cf-release/pull/1130, https://github.com/cloudfoundry/diego-release/pull/242, https://github.com/cloudfoundry-incubator/routing-release/issues/56 + related discussion on https://www.pivotaltracker.com/story/show/135771525.

Generaline running_in_container function

---

jobs/blobstore/monit
jobs/cc_uploader/monit
jobs/nsync/monit
jobs/stager/monit
jobs/tps/monit

This is the recommended approach suggested by BOSH as /var/vcap/packages should
only be used internally by the job that provides them.  For more
information see: https://www.pivotaltracker.com/story/show/150503041

Execute bpm from /var/vcap/jobs/bpm/bin

---

packages/nginx_newrelic_plugin/pre_packaging

- pre-packaging runs on the user's workstation when building the
release, so installing gems into the user's system isn't ideal
- On my Linux workstation, I have install gems using sudo and
`sudo bosh create-release` is real sketchy
- The bug that caused capi to pin bundler to 1.11 has since been fixed

Stop trying to install bundler during pre-packaging

---

jobs/nsync/spec
jobs/stager/spec

This PR adds the `windows2016` stack as a default stack (akin to `cflinuxfs2` and `windows2012R2` stacks) and the Buildpack App Lifecycle as its app lifecycle.
**Note:** This PR and the PR to `cloud_controller_ng` may touch some deprecated or soon to be deprecated components. We just added the `windows2016` stack everywhere `windows2012R2` was configured so let us know if some of these additions don't make sense and we can remove changes that are unnecessary.
Goes with https://github.com/cloudfoundry/cloud_controller_ng/pull/891

add windows2016 as a default stack

---

jobs/blobstore/spec
jobs/blobstore/templates/backup
jobs/blobstore/templates/restore

[#151210351]
We discovered that the convention is not to namespace new job-level properties with the job name, so we are modifying the property we added in a previous pull request (from tinygrasshopper)
https://github.com/cloudfoundry/capi-release/pull/56 <- original pull request, recently merged

Remove namespacing of release_level_backup property

---

jobs/cloud_controller_ng/monit
jobs/cloud_controller_ng/templates/restart_drain.rb

* Add `totalmem` stanzas to cc_ng and cc_ng_worker processes
* Update restart_drain.rb to be BPM aware (PID file location changes)
This ensures that monit settings are the same when running with `bpm.enabled`

BPM uses the same monit config as non-BPM

---

jobs/cf-admin-user/spec

This job will be added to cf-deployment's api instance_group:
```
jobs:
- name: cf-admin-user
release: capi
provides:
cf-admin-user:
as: cf-admin-user
shared: true
properties:
api_url: "https://api.((system_domain))"
ca_cert: "((router_ssl.certificate))"
admin_username: "bosh"
admin_password: "((cf_bosh_password))"
```
The pre-existing variables from cf-deployment.yml will be reused
and turned back around as a bosh link for other deployments to
discover the url/credentials for Cloud Foundry.
An example client deployment would consume the link:
```
jobs:
name: broker-registrar
release: broker-registrar
consumes:
cf-admin-user:
from: cf-admin-user
deployment: cf
```
Relates to:
* https://github.com/cloudfoundry/cf-deployment/pull/322
* …

cf-admin-user job will allow cf-deployment to expose simple link

---

jobs/cloud_controller_ng/templates/migrate_db.sh.erb

Signed-off-by: Dave Goddard <dave@goddard.id.au>
Provide an environment variable during database migrations which exposes the location of the `stacks.yml` config file.
A migration which needs to alter data to include the default stack in some situations has no reliable way of identifying the default stack. If, however, the location of the CC's `stacks.yml` file is known, a migration can read it to find out the default stack.
Used to support migration in the following [cloud_controller_ng …

Export location of stacks.yml for migrations

---

jobs/blobstore/templates/nginx.conf.erb
jobs/cloud_controller_ng/templates/nginx.conf.erb

When clients are fast and blobs are big nginx may block on sendfile
which leads to timeouts on rep (hardcoded in cacheddownloader as 10 seconds).
Here is what we see in application events when deploying many cells in parallel:
```
app.crash                 mysuperapp   index: 14, reason: CRASHED, exit_description: Downloading failed
audit.app.process.crash   web          index: 14, reason: CRASHED, exit_description: Downloading failed
```
This change ensures that nginx worker tries to serve other requests after
transferring up to 1M of data to the client.
Notes:
- 1M is arbitrary: not too small to slow transferring down and not too big to block nginx worker

Make blobstore better handle many clients

---

jobs/cc_deployment_updater/spec
jobs/cc_deployment_updater/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb

This is a follow up on [Enable pluggable container orchestration using OPI](https://github.com/cloudfoundry/cloud_controller_ng/pull/1205) in the CloudController repo. This PR adds the  properties required to enable the OPI component &mdash; `cc.opi.enabled` and `cc.opi.url` &mdash; in the `cloud_controller_ng` configuration.
/cc @julz @andrew-edgar @JulzDiverse @mnitchev @suhlig

Introduce an option to enable OPI

---

jobs/cc_deployment_updater/spec
jobs/cloud_controller_clock/spec
jobs/cloud_controller_ng/spec
jobs/cloud_controller_worker/spec

Add windows stack for the lifecycle 
This enables `cf push -s windows`

Add windows stack for lifecycle association

---

jobs/cc_deployment_updater/spec
jobs/cc_deployment_updater/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb

Make the timeouts used by diego bbs client configurable.
* An explanation of the use cases your change solves:
We noticed that the hardcoded values of 10s is not enough in environments with more than 100,000 apps. This PR allows a configuration that can be adjusted to the specific environment.
https://github.com/cloudfoundry/cloud_controller_ng/pull/1257

Introduce configurable bbs client timeouts

---

jobs/cc_deployment_updater/templates/cloud_controller_ng.yml.erb
jobs/cc_route_syncer/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb

Operators can add a list of istio domains to the `copilot.temporary_istio_domains` property in the manifest. Cloud Controller then filters routes sent to Copilot based on whether they're associated with an Istio domain.
[Tracker Story](https://www.pivotaltracker.com/story/show/159944349)
https://github.com/cloudfoundry/cloud_controller_ng/pull/1263

add copilot.temporary_istio_domains property

---

jobs/blobstore/templates/nginx.conf.erb

Enable readahead in blobstore nginx.
Improves blobstore performance on slow disks

Enable readahead in nginx

---

jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

This change is to accept an array of domains as an entry to `app_domains` in cloud_controller_ng to support populating the spec property from two different form fields.
n/a
* [n/a] I have run CF Acceptance Tests on bosh lite

Accept an array of app domains as an entry to the app_domains template property in cloud_controller_ng

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/post-start.sh.erb

This is to prevent a `cloud_controller_ng` that fails to start properly from incorrectly passing canary tests.
Don't complete `post-start` for `cloud_controller_ng` until the same healthcheck that `monit` uses passes.
Prior to this change if `cloud_controller_ng` took too long to start, `monit` would force it into a crash loop, however `bosh` would not detect the failure and thus would promote the canary to all `api` servers, eventually taking out an entire CloudFoundry installation.
See full write-up in: https://github.com/cloudfoundry/capi-release/issues/125
This PR attempts fix the `bosh` deployment so that it will correctly fail to pass the canary if `cloud_controller_ng` fails to start …

Don't complete post-start until healthcheck completes successfully

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb

This is a follow up on [Enable OPI staging](https://github.com/cloudfoundry/cloud_controller_ng/pull/1288) in the CloudController repo. This PR adds the properties required to enable staging using the OPI component — `cc.opi.opi_staging` and `cc.opi.cc_uploader_url` — in the cloud_controller_ng configuration.
We deploy Eirini using Kubernetes (instead of Diego) and run CATs apps suite on a regular basis in our [pipeline](https://ci.flintstone.cf.cloud.ibm.com/teams/eirini/pipelines/acceptance/jobs/run-core-cats/builds/12). 
cc @suhlig @julz @JulzDiverse @mnitchev

Introduce optional staging on OPI

---

jobs/cloud_controller_ng/templates/post-backup-unlock.sh.erb
jobs/cloud_controller_ng/templates/post-restore-unlock.sh.erb
src/capi_utils/monit_utils.sh

Improve DRATs reliability by improving CAPI availability in BBR scripts
Make script require more robust success responses before declaring
server to be "healthy". The number of successes and the timeout are
configurable. 
Signed-off-by: Elena Sharma <esharma@pivotal.io>
With this change, the unlock scripts for CC ng job will more reliably signal that CC is back up. 
As a result of this change the subsequent BBR jobs will not hit a 404/502 error when trying to target CC API endpoint.
A similar change had to be committed to UAA: …

Ensure that cc ng waits until provided timeout to populate routes

---

jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

[#164094017]
This adds the v2 logging endpoint to the CAPI root. We've announced deprecation of the v1 API and this change will make the v2 api more discoverable.
https://github.com/cloudfoundry/cloud_controller_ng/pull/1301

Add v2 logging endpoint to CAPI root

---

jobs/cloud_controller_ng/templates/post-backup-unlock.sh.erb
jobs/cloud_controller_ng/templates/post-restore-unlock.sh.erb

Improve PDRATs reliability by improving the way autoscaling, usage-service and notifications block on CAPI availability in their BBR scripts
Signed-off-by: Slawek Ligus <sligus@pivotal.io>
With this change, the unlock scripts for CC ng job will wait (60 seconds) until CC is probably back up.
This is similar to our previous PR, #131, but in this PR we sleep instead of attempting to check if CC is back up. This skips [all the weirdness around maintenance mode](https://github.com/cloudfoundry/capi-release/pull/131#issuecomment-473443428).
As a result of this change the …

Ensure that cc ng waits to populate routes - second try

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

The property will always come from a BOSH link and it's going to be the same for both OPI and Diego, so there's no need for this duplication.
Follow-up on [this](https://cloudfoundry.slack.com/archives/C8RU3BZ26/p1552424192298600) discussion.

Do not maintain cc_uploader_https_url property for OPI

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/templates/opi_tls.crt.erb
jobs/cloud_controller_ng/templates/opi_tls.key.erb
jobs/cloud_controller_ng/templates/opi_tls_ca.crt.erb

Add OPI client certificate keys
Allow mTLS support between Cloud Controller and Eirini OPI
https://github.com/cloudfoundry/cloud_controller_ng/pull/1357
p.s. Cloud Controller Submodule needs to be bumped.
@jpalermo && @madamkiwi

Add params to provide OPI client certificate

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_clock/templates/opi_tls.crt.erb
jobs/cloud_controller_clock/templates/opi_tls.key.erb
jobs/cloud_controller_clock/templates/opi_tls_ca.crt.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/templates/opi_tls.crt.erb
jobs/cloud_controller_worker/templates/opi_tls.key.erb
jobs/cloud_controller_worker/templates/opi_tls_ca.crt.erb

Related to this merged PR: https://github.com/cloudfoundry/capi-release/pull/143
We forgot to add these properties for the worker and clock jobs as well, oops.
Saw there was some discussion around how to deploy all the Eirini stuff with BOSH, so if you all need help with that for validating these changes, definitely feel free to let us know here and we'd be happy to pair or something to assist. 
Thanks,
Jwal + @madamkiwi

Add Eirini mTLS properties to CC clock and worker

---

jobs/cc_route_syncer/spec
jobs/cc_route_syncer/templates/cloud_controller_ng.yml.erb
spec/cc_route_syncer/cloud_controller_ng_spec.rb

[#161849257]
These changes include a PR to cloud controller that allow the VIPs it generates to be sent to envoy. In addition to that PR, we are also introducing some bosh links to the cc route syncer job from cloud controller. The cloud controller job already provides the field `internal_route_vip_range`, which the route syncer needs in order to correctly determine VIPs. 
This change allows the cc route syncer to successfully accept VIPs from cloud controller. This change also makes it so that we no longer use hard-coded vips, which prevents collision.
* Links to any …

add internal_route_vip_range to cc route syncer job

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

Related CC PR: https://github.com/cloudfoundry/cloud_controller_ng/pull/1356
Increase to give CC a softer, smoother texture.
Here is an example ops file to use with this:
```yml
---
- type: replace
path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/experimental?/thread_count?
value: 21
```

Add configuration for CC thin thread pool size

---

jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

[#168083320]
Signed-off-by: Caitlyn Yu <cyu@pivotal.io>
Add the log-cache url to templates
Promotes log-cache to first class citizen (CF CLI wants).
https://github.com/cloudfoundry/cloud_controller_ng/pull/1426

Add log cache url to root info

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb

The equivalent change was made in cloud_controller_ng by: https://github.com/cloudfoundry/cloud_controller_ng/commit/2eeee4ff1fe4deba2455993ddf9795fc389468c4
[Here's why we need it in the worker config](https://github.com/cloudfoundry/cloud_controller_ng/commit/2eeee4ff1fe4deba2455993ddf9795fc389468c4#commitcomment-35949858)
Co-authored-by: George Blue <gblue@pivotal.io>

Add `route_services_enabled` to worker config

---

jobs/cloud_controller_ng/spec

Hi. I noticed this when parsing the file with go (the YAML library errored on the duplicate field).

Remove duplicate YAML field in spec

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

* A short explanation of the proposed change: Enable settting a second token_secret to be able to rotate symmetric keys in UAA
* An explanation of the use cases your change solves: there was not the ability to rotate UAA symmetric keys prior to this without downtime.
* Links to any other associated PRs: related change in cloud_controller_ng is here ... https://github.com/cloudfoundry/cloud_controller_ng/pull/1512

Enable second token_secret for symmetric key rotation

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

Follow up of https://github.com/cloudfoundry/cloud_controller_ng/pull/1585 to pass the new config parameter to to the bosh release and be able to write an ops file for this functionality.
Merge after https://github.com/cloudfoundry/cloud_controller_ng/pull/1585  is released and integrated into CAPI-Release.

Add config parameter for new logging.anonymize_ip flag in CC

---

jobs/cloud_controller_ng/spec
scripts/detect-system-host-routes.sh

Currently cloud_controller_ng.yml has `ssh.<system_domain>` set as the endpoint for `cf ssh`.
https://github.com/cloudfoundry/capi-release/blob/44247ddb4398f6ae4bc057ca74207787e6fbb15a/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb#L120
There is no problem in the case where gorouter and ssh-proxy are co-located in the same VM like bosh-lite environment,
but if not, all access to `ssh.<system_domain>` reaches ssh-proxy.
I think it is necessary to register as system_hostnames.

Update cc.system_hostnames default

---

jobs/cc_uploader/templates/pre-start.erb

See ticket https://github.com/cloudfoundry-incubator/kubecf/issues/520 for the origin.
This PR revises the cc-uploader's `pre-start.erb` script to allow execution within a containerized deployment. It uses the same mechanism as seen in the `cc_uploader_ctl.erb` script (lines 8, 24-41) to detect execution within a container and prevent the kernel re-configuration forbidden by that environment. The original local patch simply removed these commands, leaving something which would not work in BOSH anymore. The change proposed here should not have that failing.
I have run a kubecf (containerized) deployment and smoke tests.
Both were :heavy_check_mark:

Revise the cc-uploader pre-start.erb to allow execution within a containerized deployment.

---

jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb

Service key creation is now done asynchronously in cloud controller v3 api. 
The cloud controller broker client needs access to this property hence it needs to be present in the worker config.
cloud controller config change [PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/1989)

Add `cc_service_key_client_name` to worker config

---

jobs/cloud_controller_ng/templates/bpm.yml.erb
jobs/cloud_controller_worker/templates/bpm.yml.erb
spec/cloud_controller_ng/bpm_spec.rb

Add `FOG_DEBUG` environment variable and add switch expression for different providers
Add additional `FOG_DEBUG` environment variable for Azure blobstore(fog-azure-rm changes: https://github.com/fog/fog-azure-rm/pull/431)
Add switch expression to set different environment variables for different blobstore provider. Without this sensitive information could be leaked in the logs(i.g. when "DEBUG" is enabled on azure)
We also added a simple unit test for the bpm templating. Let us know if this can be done in a nicer way :upside_down_face:

Add `FOG_DEBUG` env var and distinguish different providers

---

jobs/cloud_controller_ng/monit
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cc-drain.rb.erb
jobs/cloud_controller_ng/templates/restart_drain.rb.erb
spec/cloud_controller_ng/drain_spec.rb

Currently the nginx timeout for graceful shutdown is hard coded to 30 secs. If requests take longer than this (e.g. `v2/services` on big foundries) they'll be terminated. Making this configurable will allow operators to prevent (too many) failed requests during monit restarts. See `cloud_controller_ng` https://github.com/cloudfoundry/cloud_controller_ng/pull/2138.  
For the same reason the number of monit cycles for detecting constant high memory consumption should be configurable. 
* Links to any other associated PRs:
https://github.com/cloudfoundry/cloud_controller_ng/pull/2138

Shutdown nginx timeout

---

jobs/cloud_controller_ng/templates/nginx.conf.erb

Hide header `X-USER-GUID` from client. Header was newly introduced in cc_ng with https://github.com/cloudfoundry/cloud_controller_ng/pull/2167
It can be used in nginx access logs, e.g. with `user_guid=$upstream_http_x_user_guid`
This makes it easier for us track/ debug requests with the nginx logs.
* https://github.com/cloudfoundry/cloud_controller_ng/pull/2167

Hide user guid header from client

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/nginx.conf.erb
spec/cloud_controller_ng/nginx_spec.rb

With this PR the characters escaping used for logging variables to the nginx access log can be set to `json`. This allows changing the log format to a JSON string (e.g. `{"key":"$variable"}`) and getting properly escaped JSON logs.
With Logstash the parsing of JSON-formatted logs becomes easier and is more flexible (i.e. adding a new field does not require the parser to be changed).

Allow configuration of different (i.e. json) escaping for access log

---

jobs/cloud_controller_ng/monit
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/ccng_monit_http_healthcheck.sh.erb
jobs/cloud_controller_ng/templates/cloud_controller_api_health_check.erb
jobs/cloud_controller_ng/templates/restart_drain.sh.erb
jobs/cloud_controller_ng/templates/shutdown_drain.rb.erb
spec/cloud_controller_ng/healthcheck_spec.rb

A failing health check stops the Cloud Controller without invoking the `restart_drain` script. BPM will terminate the process with a grace period of 20s; any long-running requests will be cancelled and lead to a `502 Bad Gateway` error at the client. With this change the `restart_drain` script will also be called for failing health checks, giving long-running requests a higher ([configurable](https://github.com/cloudfoundry/capi-release/blob/2b52d846f82c7dbe893ffc21f879c15a3fa1da36/jobs/cloud_controller_ng/spec#L870)) timeout.
On large foundations (i.e. many orgs, …

Invoke restart drain for failed healthcheck

---

packages/libpq/README.md
packages/libpq/packaging
packages/libpq/spec

cf-deployment currently uses [postgres-release 43](https://github.com/cloudfoundry/postgres-release/releases), which comes with postgres 11.10.
libpq in capi-release is still on postgres 11.5. According to postgres its best practice to have the client library at least on the level of the server. Newer version of the postgres client / libpq are backward compatible, the server may not be backword compatible. Therefore it would be good to bump libpq in capi-release to the same level as postgres in postgres release. Also the update addresses vulnerabilities in postgres.
We have build a capi-release with the updated libpq, deployed it with bosh-lite and run smoke tests.
This is similar to the PR from one and a half year age: [bump libpq to postgres …

Update psql lib to postgres version 11.11

---

jobs/cc_deployment_updater/spec
jobs/cc_deployment_updater/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

Draft ready for https://github.com/cloudfoundry/cloud_controller_ng/pull/2351
Expose configuration of database connection expiration settings
Allow BOSH users to configure DB connections to expire due to long running connections consuming and not release DB resources
https://github.com/cloudfoundry/cloud_controller_ng/pull/2351

Add configuration for connection expiration settings

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

Hi CAPI friends!
This is a PR to toggle the behavior of the new `space supporter` role (previously known as `space_application_supporter`). It introduces a new temporary flag in the cloud_controller_ng spec.
**NOTE**: this property hooks into a renamed property in [this CCNG PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/2375) that has not been merged yet. While that PR is not necessarily a blocker, this property will be ineffective until those changes are merged into CCNG.
Best,
Belinda

Add flag to toggle space supporter role

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

Allow configuring of the threshold above which large queries should be logged
We want to know which endpoints are making queries that return a lot of rows which causes the main CC process to have to parse rows slowly. This is mainly an issue for the API as it slows down requests which in turn slows down other requests etc. as they are on a shared process so not going to worry about extending this config to other jobs yet.
https://github.com/cloudfoundry/cloud_controller_ng/pull/2338

Configure query size log threshold

---

jobs/cloud_controller_ng/monit
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/ccng_monit_http_healthcheck.sh.erb

Although the health endpoint only returns HTTP status code 200 under normal circumstances there might be issues with either the rack middleware or nginx resulting in HTTP error response codes. Consistently failing health checks should gracefully shutdown and restart CC (as done by the `restart_drain` script).
To overcome situations when CC starts up slow (e.g. due to database overload) an additional monit check for the `nginx_cc` process has been added. As Nginx communicates with CC via a unix socket, it should not run unless the socket is ready. If the socket is unavailable for 10 minutes (configurable) a graceful shutdown and restart is triggered.
We tested the changes in this PR as follows:
- We modified the `RequestMetrics` middleware to raise an error when there were too many …

Fail monit health check on 4xx/5xx responses from CC

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

* A short explanation of the proposed change
This flag was used while we were adding the new role, now that the role is ready to go so we can remove the flag
Issue: https://github.com/cloudfoundry/cloud_controller_ng/issues/2469
ccng PR: https://github.com/cloudfoundry/cloud_controller_ng/pull/2490

Remove `temporary_enable_space_supporter_role` flag

---

jobs/cloud_controller_ng/templates/restart_drain.sh.erb
src/capi_utils/monit_utils.sh

In case the monitoring is triggered before the unmonitoring finished, the jobs remain in an unmonitored state. Make use of the helper function `monit_unmonitor_job` from `monit_utils.sh` as it waits until unmonitoring succeeded. Add `monit_monitor_job` function to `monit_utils.sh`.

Ensure that job is unmonitored before monitoring it again

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

Add configuration for service broker rate limiting
Allow operators to limit how many concurrent service broker requests a user can make per broker
https://github.com/cloudfoundry/cloud_controller_ng/pull/2563

Add service broker concurrent rate limit config

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

Expose `use_optimized_json_encoder` as an experimental config property.
Related CCNG PR: https://github.com/cloudfoundry/cloud_controller_ng/pull/2481

Introduce experimental use_optimized_json_encoder configuration

---

jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

I originally forgot some templating syntax and the fix bumped this into
the rate_limiting object but it is actually a root config option (since
it doesn't really apply to the classic rate limiting)

Fix broken concurrent requests config

---

packages/cloud_controller_ng/packaging

Add `libpq/bin` directory to path
The libpq/bin directory contains pg_config which pg_sequel calls out to when compiling the C extension
https://github.com/cloudfoundry/cloud_controller_ng/pull/2595

Put libpq/bin directory on PATH

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb

This PR makes the cloud_controller_ng parameter which is introduced in https://github.com/cloudfoundry/cloud_controller_ng/pull/2667 configurable.

Introduces exponential backoff config parameter

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

This change allows operator to set the `cc.jobs.priorities` parameter introduced with this [ccng PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/2693).
As a platform operator I want to prioritize e.g. CF-Push over create service operations via an ops file.
- Depends on https://github.com/cloudfoundry/cloud_controller_ng/pull/2693

Introduce optional job priorities parameter

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/post-backup-unlock.sh.erb
jobs/cloud_controller_ng/templates/post-restore-unlock.sh.erb

unlock
- post-start waits for server to become healthy with
api_post_start_healthcheck_timeout_in_seconds, so consistent now
across post-backup and post-restore
- still uses default of 60 seconds
- user can expect the same time now
Authored-by: Michael Oleske <moleske@pivotal.io>

Use post_bbr_healthcheck_timeout_in_seconds for backup and restore

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

`/var/vcap/sys/log/cloud_controller_ng/telemetry.log` was the hard-coded value of the `telemetry_log_path`. When setting the new config option `cc.telemetry_logging_enabled` to `false` (default value is `true`), `telemetry_log_path` will be omitted.
Requires cloudfoundry/cloud_controller_ng#2744

Provide means to disable telemetry logging

---

config/blobs.yml
jobs/nfs_mounter/templates/pre-start.sh.erb
packages/nfs-debs/README.md
packages/nfs-debs/spec

- bionic stemcells are released and this adds nfs-common and its
dependencies for bionic
Authored-by: Michael Oleske <moleske@pivotal.io>
This fixes the ripley environment and we can unpause the pipeline after merging this

Add bionic nfs blobs

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/bin/dns/healthy.sh.erb

This commit resolves the core problem in the CC-112 Jira ticket. It
-effectively- instructs Bosh DNS to run the same Cloud Controller health
checking script that `route-registrar` uses to decide whether CCNG's
route should be removed or reinstated in Gorouter.
Because these two health check scripts are run by two separate
components, each with their own start time, and each with its own
frequency with which it will collect and report health check
information, there will inevitably be gaps between the time CCNG is
reported as unhealthy in one system and it is reported as unhealthy in
the other. This seems to be unavoidable.
Co-authored-by: David Alvarado <alvaradoda@vmware.com>
Co-authored-by: Kenneth Lakin <klakin@vmware.com>
Thanks for contributing to the `capi_release`. To speed up the …

Adds health check script for Bosh DNS

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/nginx.conf.erb
jobs/cloud_controller_ng/templates/prom_scraper_config.yml.erb
jobs/cloud_controller_ng/templates/prom_scraper_mtls.conf
jobs/cloud_controller_ng/templates/scrape.crt.erb
jobs/cloud_controller_ng/templates/scrape.key.erb
jobs/cloud_controller_ng/templates/scrape_ca.crt.erb

NOTE: This PR is dependent on this PR to `cloud_controller_ng`: https://github.com/cloudfoundry/cloud_controller_ng/pull/2781
This PR contains the changes required to support the work in Cloud Controller NG's PR 2781, linked to above. You _could_ merge this PR before 2781 is merged, and no harm would be done, but it would be best to not do that.
**Notable technical details:**
This commit adds two new Bosh Release configuration parameters: `cc.prom_metrics_server_tls_port` and `cc.prom_scraper_tls`. They are fed to a new "server" in the release's nginx configuration. For more details, check out the commit message and code changes.
I have not run CF Acceptance Tests, but I _have_ tested that the release can deploy multiple instances of the Dora CF App, both with cf-deployment and with …

Adds support for prom_scraper metrics endpoint

---

config/blobs.yml
packages/nginx/README.md
packages/nginx/packaging
packages/nginx/spec
packages/nginx_webdav/packaging
packages/nginx_webdav/spec

The current nginx is not compatible with OpenSSL 3.0, causing compilation failures on the upcoming Jammy Jellyfish-based stemcells.
This commit fixes that by bumping nginx 1.20.1 → 1.21.6.
Fixes, during compilation phase:
```
Task 63223 | 13:39:29 | Compiling packages: nginx_webdav/... (00:02:48)
In file included from src/event/ngx_event_openssl.h:22,
from src/core/ngx_core.h:84,
from src/event/ngx_event_openssl.c:9:
/usr/include/openssl/engine.h:493:27: note: declared here
493 | OSSL_DEPRECATEDIN_3_0 int ENGINE_free(ENGINE *e);
|                           ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:857: objs/src/event/ngx_event_openssl.o] Error 1
make: *** [Makefile:10: build] Error 2
```
(I'd do it myself, except I don't have creds to the …

Use OpenSSL 3.0-compatible nginx

---

config/blobs.yml
packages/mariadb_connector_c/README.md
packages/mariadb_connector_c/packaging
packages/mariadb_connector_c/spec

The current mariadb connector c is not compatible with OpenSSL 3.0, causing compilation failures on the upcoming Jammy Jellyfish-based stemcells.
This commit fixes that by bumping mariadb connector c 2.3.5 → 3.3.1
Error that it fixes:
```
Task 63221 | 13:27:45 | Compiling packages: mariadb_connector_c/214543bbb1d7499acdbdb44a7323430a635a77fa004f4fd4dbaf4e544291b072 (00:03:05)
CMake Error at cmake/ConnectorName.cmake:30 (ENDMACRO):
Flow control statements are not properly nested.
nginx/3f524e8d016595416a9ad5dac6bb9490a0eb765a85c76c47635b447184ef691d (00:03:25)
```
Co-authored-by: Brian Cunnie <bcunnie@vmware.com>
Co-authored-by: Michael Oleske <moleske@pivotal.io>
* …

Use OpenSSL 3.0-compatible mariadb connector

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/nginx.conf.erb
jobs/cloud_controller_ng/templates/prom_scraper_config.yml.erb
jobs/cloud_controller_ng/templates/prom_scraper_mtls.conf
jobs/cloud_controller_ng/templates/scrape.crt.erb
jobs/cloud_controller_ng/templates/scrape.key.erb
jobs/cloud_controller_ng/templates/scrape_ca.crt.erb

Once https://github.com/cloudfoundry/cf-deployment/pull/970 has been
pulled in can we re-introduce this change
This reverts commit dd812167b9c6105d64ab83e0b7366424f7547eab.
Once https://github.com/cloudfoundry/cf-deployment/pull/970 has been
pulled in can we re-introduce this change

Add prom_scrapper endpoint

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

Add configuration for the v2 API rate limiter. It calculates the `per_process` limit based on the number of instances similar to the general rate limiter. More details about the v2 rate limiter can be found in https://github.com/cloudfoundry/cloud_controller_ng/pull/2882
As an operator I want to enable/configure the rate limit v2 API calls for regular (incl. unauthenticated) and admin users
- https://github.com/cloudfoundry/cloud_controller_ng/pull/2882

Add configuration for v2 API rate limiter

---

config/blobs.yml
packages/nfs-debs/README.md
packages/nfs-debs/spec

Authored-by: Seth Boyles <sboyles@pivotal.io>

nfs-common now depends on libevent-core, not libevent

---

jobs/nfs_mounter/templates/pre-start.sh.erb

Co-authored-by: Michael Oleske <moleske@pivotal.io>
Co-authored-by: David Alvarado <alvaradoda@vmware.com>
- nfs_mounter needs to install libevent-core not libevent
- fixes the pipeline

Correct nfs_mounter pre-start to install libevent-core on jammy

---

jobs/cloud_controller_worker/templates/bpm.yml.erb

`RAILS_ENV` should be set  to `production` to prevent rails/active support from reloading routes. In context of a cc worker this feature is not needed because there are no routes.
Related to #262

Set 'RAILS_ENV' to `production`

---

jobs/cloud_controller_ng/templates/bpm.yml.erb

On local workers `RAILS_ENV` should be set  to `production` to prevent rails/active support from reloading routes. In context of a cc worker this feature is not needed because there are no routes.
Same as #263 for dedicated workers.
Related to #262

Set `RAILS_ENV` to `production` on local worker

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb

- add a default rate limit to capi
- Remove cc.temporary_use_logcache property
New cloud controllers don't support using Traffic Controller for
container metrics, so removing this property from capi-release
Capi release changes for cloud controller ng for log rate limiting feature
https://github.com/cloudfoundry/cloud_controller_ng/pull/2900

Log rate limit changes

---

jobs/cloud_controller_ng/spec

We are updating the functionality of this here: https://github.com/cloudfoundry/cloud_controller_ng/pull/2962 and we believe the new behavior should be on by default.

Update log_audit_events cloud controller property to true by default

---

jobs/cc_deployment_updater/templates/bin/cc_deployment_updater.erb
jobs/cloud_controller_clock/templates/bin/cloud_controller_clock.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/bin/cloud_controller_ng.erb
jobs/cloud_controller_ng/templates/bin/local_worker.erb
jobs/cloud_controller_worker/templates/bin/cloud_controller_worker.erb

enables YJIT compiler on CC jobs.
YJIT is optimized for long running processes, trading a higher memory usage for speed improvements. 
Most of the jobs worked fine without alteration with default config values, but I did have to bump up the memory thresholds on the cc-worker.
for more on running YJIT: 
https://github.com/ruby/ruby/blob/master/doc/yjit/yjit.md
https://news.ycombinator.com/item?id=29161810

Add experimental flag to enable YJIT compiler

---

packages/cloud_controller_ng/packaging
packages/mariadb_connector_c/packaging
packages/mariadb_connector_c/spec
src/mariadb-customization/mariadb_config-wrapper.sh

Upgrading from mariadb connector 2.x to 3.x the mariadb_config started returning absolute paths rather than relative paths to the mariadb package folders. These absolute paths change when exporting the release from one director to another.
There doesn't seem to be a set of flags we can manually pass to build the mysql2 gem so we were forced to add a wrapper script that replaces the absolute paths with the relative paths.
Mostly stolen from here: https://github.com/cloudfoundry/bosh/commit/5a9b68c2c9402943afd2bcc7a19aaf6437b9bbbf

Add mariadb_config wrapper script to fix symlink paths

---

jobs/cloud_controller_ng/templates/nginx.conf.erb
jobs/cloud_controller_ng/templates/nginx_external_endpoints.conf.erb

This change opens a new endpoint in the nginx.conf that was added to the internal syslog_drain_controller lately.
The PR that introduces the new endpoint can be found [here](https://github.com/cloudfoundry/capi-release/commit/b3ae4a6bf12b153ca3e5a4f74fa5860c6eb562d8).

Add v5 endpoint for drain-controller to nginx.conf

---

jobs/blobstore/spec

We were running into this limit when testing pushes of large apps. Reviewing the history of this it does not seem like a valuable limit. There are already several upstream limits in place for max Cloud Controller upload size as well as max packaage size.
We've left the configuration option in place in case there are use cases where you want to have a limit but we believe unlimited is a more sane default.
https://github.com/cloudfoundry/cloud_controller_ng/pull/3010

Update the blobstore max_upload_size default to remove upload size limit

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

Add parameter to configure the max thread number for puma workers
Related to https://github.com/cloudfoundry/cloud_controller_ng/pull/3063

Make puma max threads configurable

---

jobs/cloud_controller_ng/templates/restart_drain.sh.erb

Ensure that the drain log dir exists

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

mTLS is required to communicate with the internal api. Thus internal user and password can be removed. 
Can be merged after CCNG PR [#3134](https://github.com/cloudfoundry/cloud_controller_ng/pull/3134) (should be merged first)

Remove `cc_internal_api_user` and `cc_internal_api_password`

---

jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/stacks.yml.erb

cloud_controller_ng stacks.yml
- when pushing an app with a buildpack not available for cflinuxfs3 and not specifying the stack, you can get an error like ``` For application 'myapp': Buildpack "somebuildpack" must be an existing admin buildpack or a valid git URI ```
- this happens because the cc.stacks and cc.default_stack was only configured in cloud_controller_ng/spec and not duplicated to cloud_controller_worker/spec
- this commit uses <link> like cc_deployment_updater since there's not much reason we would want this different

Use link for cloud_controller_worker stacks.yml to match

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_ng/spec

- default value is right below and the description isn't passed outside of the spec
- also changed some phrasing that implied it was a form
clean up some phrasing
builds on https://github.com/cloudfoundry/capi-release/pull/300

Remove redundant default information in spec descriptions

---

jobs/cc_deployment_updater/spec
jobs/cloud_controller_clock/spec
jobs/cloud_controller_ng/spec
jobs/cloud_controller_worker/spec

- Only add cflinuxfs4 to properties that are not overridden in cf-deployment.
- Not sure if we need the stack configuration in all these jobs, but they are there, so I updated them.
[cloudfoundry/cf-deployment#989]
[cloudfoundry/cf-deployment#1008]
> Add [cflinuxfs4](https://github.com/cloudfoundry/cflinuxfs4) to some default configuration values. These properties currently use the default value in cf-deployment.
> The Ubuntu version backing cflinuxfs3 will leave support in April 2023. App developers need access to cflinuxfs4, so they can start migrating off of …

Add cflinuxfs4 to default configuration to job specs

---

jobs/cloud_controller_ng/templates/post-backup-unlock.sh.erb
src/capi_utils/monit_utils.sh

Previously the unlock health check failed if any single VM was unhealthy because it used the healthz endpoint over a local route

Allow BBR post unlock to proceed if CC api is remotely available

---

jobs/cc_deployment_updater/spec
jobs/cloud_controller_clock/spec
jobs/cloud_controller_ng/spec
jobs/cloud_controller_worker/spec
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

Now with cf-deployment v28.0.0, the cflinuxfs4 is set as the default stack. This PR aims to removes cflinuxfs3 stack configuration for spec jobs related to cc and changes the defaults. Though, the cflinuxfs3 related configuration entries are still kept in the cf-deployment(overridden).

Remove cflinuxfs3 and change defaults to cflinuxfs4

---

config/blobs.yml
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/bpm.yml.erb
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/redis/monit
jobs/redis/spec
jobs/redis/templates/bpm.yml.erb
jobs/redis/templates/pre-start.sh.erb
jobs/redis/templates/redis-cli.sh.erb
packages/redis/README.md
packages/redis/packaging
packages/redis/spec
spec/cloud_controller_ng/bpm_spec.rb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb
spec/redis/monit_spec.rb

- Redis will be used for rate limiting and (at a later point in time) also for metrics.
- The monit process will only be started if either the Puma webserver is used or `cc.experimental.use_redis` is set to `true` (defaults to `false`).
- If Redis is used, the CC config `redis.socket` is set; this switches the rate limit implementation from using in-memory counters to Redis.
See also cloudfoundry/cloud_controller_ng#3290.

Add Redis job

---

jobs/cc_deployment_updater/spec
jobs/cc_deployment_updater/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_clock/templates/opi_tls.crt.erb
jobs/cloud_controller_clock/templates/opi_tls.key.erb
jobs/cloud_controller_clock/templates/opi_tls_ca.crt.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/templates/kubernetes_ca.crt.erb
jobs/cloud_controller_ng/templates/opi_tls.crt.erb
jobs/cloud_controller_ng/templates/opi_tls.key.erb
jobs/cloud_controller_ng/templates/opi_tls_ca.crt.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/templates/opi_tls.crt.erb
jobs/cloud_controller_worker/templates/opi_tls.key.erb
jobs/cloud_controller_worker/templates/opi_tls_ca.crt.erb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

- could put back some to help with upgrades since removing a property is usually a breaking change.  But the thought process here is that this wouldn't break bosh based cloud foundries cause the defaults are false.  Needs testing with the correct cloud controller branch still
Since [capi-k8s-release](https://github.com/cloudfoundry/capi-k8s-release) and [cf-for-k8s](https://github.com/cloudfoundry/cf-for-k8s) are both deprecated and not supported because of [korfi](https://github.com/cloudfoundry/korifi/), it seemed like a reasonable thing to remove kubernetes related code to reduce complexity (maybe)
This was not done …

Remove kubernetes configuration

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

https://github.com/cloudfoundry/cloud_controller_ng/pull/3353 introduced a new optional parameter `max_total_results` to prevent requests with a large number of total results (`per_page * page`) as those requests can cause expensive db queries.
This PR allows operators to configure the maximum number of total results via the parameter `cc.renderer.max_total_results`.
Related to https://github.com/cloudfoundry/cloud_controller_ng/pull/3353

Add optional cc `max_total_results` parameter

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_clock/cloud_controller_clock_spec.rb

So far failed_jobs was running once per day. We want to let it run more often, therefore we need to add the necessary params.
Failed_jobs is changed to also cleanup failed entries from the delayed_jobs table that exceeds a defined maximum number of entries in order to prevent overload of the db. The new parameter max_number_of_failed_delayed_jobs is optional. 
With this change the job should runs more often than once per day (default is every 4h) to ensure db is not overloaded.
Related to https://github.com/cloudfoundry/cloud_controller_ng/pull/3346

The failed_jobs cleanup job should run more often than once per day

---

packages/redis/packaging

The root dir of the Redis tar file can have various names depending on where/ how it is downloaded:
- When the tar is downloaded via the Concourse 'github-release-resource' the dir will be named 'redis-redis-<commit-hash>'.
- However when the tar is manually downloaded from the redis github release (e.g. https://github.com/redis/redis/archive/refs/tags/7.0.12.tar.gz) the dir will be named 'redis-<version-number>'
-> All other files of the tar are identical as they are based on the same github release.
To avoid packaging errors during deploy time this change ensures that the extracted root dir of the tar file will be named 'redis-<version-number>'. This will also prevent version conflicts.

Extract Redis tar more resilient

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb

The `uaa.clients.cc_service_broker_client` property is deprecated for years, so it's time to get rid of it.

Remove deprecated UAA client

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/nginx.conf.erb
jobs/cloud_controller_ng/templates/prom_scraper_config.yml.erb
jobs/cloud_controller_ng/templates/prom_scraper_mtls.conf
jobs/cloud_controller_ng/templates/scrape.crt.erb
jobs/cloud_controller_ng/templates/scrape.key.erb
jobs/cloud_controller_ng/templates/scrape_ca.crt.erb
spec/cloud_controller_ng/nginx_spec.rb

One more attempt at https://github.com/cloudfoundry/capi-release/pull/240
Now we don't set up prom scraper mtls if any scraper property is missing
When https://github.com/cloudfoundry/cf-deployment/pull/970 is merged, we won't need to check if the property is set

Add prom scraper endpoint

---

jobs/cc_deployment_updater/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb

ccng allows to configure storage options for the gcp fog library. This can be done via the 'fog_gcp_storage_options' parameter. Related ccng PR: [#3463](https://github.com/cloudfoundry/cloud_controller_ng/pull/3463) Commit: 6a747fe3110cd27a0383b83355f65e65a4564f1a
This change introduces 'fog_gcp_storage_options' parameter in capi-release.

Add 'fog_gcp_storage_options' parameter

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/prom_scraper_config.yml.erb
spec/cloud_controller_ng/prom_scraper_spec.rb

Introducing a flag which, when set to true, will render the prom_scraper_config.yml empty and therefore it will be ignored by the prom_scraper. This is useful if you want to use another scraper.

Add config flag to disable prom_scraper

---

jobs/cloud_controller_ng/spec

In order to support new versions of the Java buildpack, and CNBs in the future, we should increase the default max upload-able file size to 2GB. See this issue: 
- https://github.com/cloudfoundry/java-buildpack/issues/1035
[#186470719](https://www.pivotaltracker.com/story/show/186470719)

Increase default max nginx upload size to 2GB

---

jobs/cloud_controller_ng/templates/ccng_monit_http_healthcheck.sh.erb

Addresses https://github.com/cloudfoundry/capi-release/issues/364 health check will wait and retry if Nginx is not available.
This change allows Nginx and webserver to start without monit interruption.

Make Nginx healthcheck script to tolerate unavailability

---

config/blobs.yml
jobs/cc_deployment_updater/templates/bin/cc_deployment_updater.erb
jobs/cloud_controller_clock/templates/bin/cloud_controller_clock.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/bin/cloud_controller_ng.erb
jobs/cloud_controller_ng/templates/bin/local_worker.erb
jobs/cloud_controller_worker/templates/bin/cloud_controller_worker.erb
packages/jemalloc/README.md
packages/jemalloc/packaging
packages/jemalloc/spec

Jemalloc is an alternative malloc implementation which improves memory fragmentation.
It also reduces the overall memory consumption and thus might be beneficial when running on puma.
Further information can be found in this article about malloc and jemalloc: https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html
This change adds the jemalloc packages and introduces the config property `cc.experimental.use_jemalloc_memory_allocator` to enable jemalloc (default is false).

Add experimental jemalloc support

---

spec/.rubocop.yml

- it was bothering me.  And luckily no rubocop changes were needed to the test files

Fix rubocop configuration warning

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

Set default value to `true` to keep the current behaviour.
See also https://github.com/cloudfoundry/cloud_controller_ng/pull/3562.

Add legacy_md5_buildpack_paths_enabled param

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

When the `enable_statsd_metrics` configuration option is set to `false`, metrics on API VMs will be sent exclusively via Prometheus. The default behavior is `true`, where metrics are sent using both StatsD and Prometheus.

Add config option to disable statsd metrics on api vms

---

jobs/rotate_cc_database_key/spec
jobs/rotate_cc_database_key/templates/cloud_controller_ng.yml.erb
spec/rotate_cc_database_key/rotate_cc_database_key_spec.rb

The rotate-cc-database-key errand inherits the max_connections settings from ccng. With this PR, we introduce a config attribute to override max_connections from the cloud_controller_db link.

Add config attribute to override max_con for rotate-cc-database-key errand

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_local_worker_override.yml.erb
spec/cloud_controller_ng/cloud_controller_local_worker_override_spec.rb

Before this PR, the same config file was used for both ccng and the (two) cc local workers. This dedicated file aims to decouple this bond and provide a way to override the configurations for cc local workers.

Add dedicated config file for cc local workers

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

Currently, with Puma, all processes (i.e. main + Puma workers) is configured with the same cc db max_connections. This PR aims to introduce new config attribute (max_db_connections_per_process / optional). If not specified, the default db max_connections from cc_ng will be used.

Introduce new config attribute for Puma

---

jobs/blobstore/spec
jobs/blobstore/templates/blobstore.conf.erb
jobs/blobstore/templates/blobstore_public.crt.erb
jobs/blobstore/templates/blobstore_public.key.erb

Currently, the package and droplet download/upload endpoints redirect to the public port of the singleton-blobstore (if used) which does not support TLS.  This adds a TLS server to the singleton-blobstore's nginx conf. 
This change was designed to be consumed without any changes from a bosh manifest/cf-deployment.  That is, not supplying a SSL certificate in the manifest will simply cause the TLS server to not be render to the blobstore's nginx conf, and the download/upload endpoints will continue to redirect to the non-TLS port.  There will be a corresponding PR to cf-deployment soon, and some time after that is merged, we can remove the non-TLS ports entirely.

Add public TLS endpoint for blobstore

---

jobs/cc_deployment_updater/spec
jobs/cloud_controller_clock/spec
jobs/cloud_controller_worker/spec
jobs/rotate_cc_database_key/spec
jobs/rotate_cc_database_key/templates/bin/run.erb

Some jobs consume the linked property `use_jemalloc_memory_allocator` to enable jemalloc but don't specify the required package in their spec file. Resulting in jemalloc not being used.
Thus the missing packages need be added.
Related to commit 62c5d07bb28e081bcdb21b4e2517fdd0158e6489/ PR #367 where we added experimental jemalloc support for all ccng based jobs.

Add jemalloc package to missing job specs

---

jobs/cloud_controller_clock/spec

4 * 60 * 60 = 14400, not 144000

Fix default frequency_in_seconds

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

This change enables operators to configure
the new config property `max_migration_statement_runtime_in_seconds` see https://github.com/cloudfoundry/cloud_controller_ng/pull/3633.

Add `max_migration_statement_runtime_in_seconds` config property

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/migrate_db.sh.erb

The number of database migrations retries should be configurable for operators. The default remains the same with 3.

Make number of db migration retries configurable

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

Add optional parameter to set postgres worker mem for db migrations.
- https://github.com/cloudfoundry/cloud_controller_ng/pull/3738

Add optional parameter to set postgres worker mem for db migrations

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

Allow operators to configure Cloud Controller to support ASGs with comma-delimited destinations.
For example, the following ASG definition would be valid:
```
[
{
"protocol": "tcp",
"destination": "1.2.3.4,10.0.0.0/24,25.0.0.0-26.0.0.0",
"ports": "65432",
"description": "Valid comma delimited list of destinations"
}
]
```
Currently, if a developer wants to open connections from their cf app to two non-consecutive IP addresses (e.g. 8.8.8.8 and 10.10.10.10), they'd have to create two separate ASGs. This creates duplication and performance implications on some large environments with many ASGs that are also running networking fabrics _other_ than silk.
One way to reduce said duplication is to enable comma-delimited destinations, so that the firewall rules are consolidated.
- …

Add config for comma-delimited destinations in ASGs

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

This PR adds a config flag to enable dynamic job priorities.
https://github.com/cloudfoundry/cloud_controller_ng/pull/3703

Add flag with which dynamic job priorities can be enabled

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb

New config property `service_operations_initial_cleanup.frequency_in_seconds` for the background cleanup job.
The background job cleans up operations stuck in state 'create'/'initial' (sets them to 'failed' so that users can delete the associated entity).
https://github.com/cloudfoundry/cloud_controller_ng/pull/3742

New config parameter for cleanup job

---

packages/nginx/packaging
packages/nginx_webdav/packaging

We observed that the server name (Nginx) is leaked in the header and in the body of an error message.
To bolster the security stance of the web application and reduce the likelihood of information exposure, it's highly advised to refrain from divulging the server's name and version in any response data, including error messages.
What the PR changes: adjust NGINX sources by using sed to perform an in-place substitution of the server name before building nginx (Found by @philippthun [here](https://medium.com/@getpagespeed/how-to-remove-the-server-header-in-nginx-e74c7b431b))
With this change the server name does not appear any more in any response/error message.

Remove nginx from response headers and error responses

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

Operators would like to configure the optional ccng config property `migration_psql_concurrent_statement_timeout_in_seconds`
Related to https://github.com/cloudfoundry/cloud_controller_ng/pull/3772

Introduce parameter `migration_psql_concurrent_statement_timeout_in_seconds`

---

config/blobs.yml
packages/libpq/README.md
packages/libpq/packaging
packages/libpq/spec

Bump libpq to v16.2
Postgres 16 is the default in cf-deployment: https://github.com/cloudfoundry/cf-deployment/commit/137a99e0443e239184d00861953d078167a97a76

Bump libpq to v16.2

---

jobs/cloud_controller_ng/spec

The default value for this property is `false` in cf-deployment since v40.

Default legacy_md5_buildpack_paths_enabled to false

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

This feature flag for the cloud controller will allow the users to enable/disable the usage of window pagination when accessing the database for all the tables. By default, the behavior is to use the window pagination.
This change will allow the operator to disable the window for pagination for all the tables in a single place. Will also allow us to debug possible performance issues with the window pagination in other tables.
Flag implemented in https://github.com/cloudfoundry/cloud_controller_ng/pull/3802

Add feature flag ccdb.enable_paginate_window

---

spec/.rubocop.yml

- removes warning that rubocops aren't enabled
- if ccng gets them, why not capi release?

Add new rubocops to .rubocop.yml

---

jobs/cloud_controller_ng/templates/prom_scraper_config.yml.erb

Resolves https://github.com/cloudfoundry/cloud_controller_ng/issues/3842 
This add the `origin: cc` label to every prom metric emitted by cc.
Before:
```
origin:"" eventType:ValueMetric timestamp:1716927345188339944 deployment:"cf-593c65d5b217b0a112ad" job:"control" index:"66379c89-3e02-4322-9555-004ce8183ea5" ip:"10.0.4.7" tags:<key:"instance_id" value:"66379c89-3e02-4322-9555-004ce8183ea5" > tags:<key:"product" value:"Small Footprint VMware Tanzu Application Service" > tags:<key:"source_id" value:"cloud_controller_ng" > tags:<key:"system_domain" value:"xxx" > valueMetric:<name:"cc_requests_outstanding_total" value:1 unit:"" >
```
After:
```
origin:"cc" eventType:ValueMetric timestamp:1718239416878685187 deployment:"cf-a31da169de4fe97cda42" job:"cloud_controller" …
```

Update prom_scraper_config to add origin: cc label

---

jobs/cloud_controller_ng/spec

Add info on how the format of the version number of the min cf cli version should be configured
Description enhancement
User can read in config description how to format cf cli version number

Add info on how the format of the version number of the min cf cli version should be configured

---

.github/workflows/gh_pages_docs_v2.yml

This is a move of [CCNG PR #3874](https://github.com/cloudfoundry/cloud_controller_ng/pull/3874)
- The original location was unsatisfactory since there is already a GitHub Pages site bound to the CCNG repo.
- Detail from the original PR, copied for convenience:
- Serve the V2 API docs as static GitHub Pages assets, deployed via GitHub Actions
- As part of the VMware->Broadcom migration, the infrastructure hosting the current v2 apidocs is being replaced. This provides an opportunity to sunset unneeded apps, lowering the project's maintenance & support burden.
_Links to any other associated PRs_
https://github.com/cloudfoundry/cloud_controller_ng/pull/3874 - as above
https://github.com/cloudfoundry/capi-release/pull/438 - going to be closed since the trigger direction will be reversed with …

GitHub Pages V2 Docs

---

CNAME

This PR is needed to configure a custom domain for the V2 docs' GitHub Pages, as per [Configuring a subdomain in the Pages docs](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain)
The Pages site is currently pushed to the default for this repository, https://cloudfoundry.github.io/capi-release/
Links to any other associated PRs
https://github.com/cloudfoundry/capi-release/pull/440
N/A - no code changes to the release / anything that would be covered by CATS - this is a `CNAME` file

Add CNAME for V2 docs

---

jobs/cc_deployment_updater/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_clock/cloud_controller_clock_spec.rb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

This new property enables app logs in the format APP/REV/<version>/PROC/WEB/<process>.
We added this property to the following jobs:
* cloud_controller_ng
* cc_deployment_updater
* cloud_controller_clock
* cloud_controller_worker
We believe cloud_controller_worker does not send desired_lrp actions to diego, however we were not completely sure so we added it just incase.
This will be used for Canary Deployments to identify which logs come from with revision of the app

Add app_log_revision property

---

jobs/cloud_controller_ng/templates/pre-start.sh.erb

Running the `stack_check` before the initial DB setup fails, as it waits for the database schema to be current (`Sequel::Migrator.is_current?`).

Run stack_check after DB migrations and seeds

---

jobs/cloud_controller_ng/templates/pre-start.sh.erb

This reverts commit f445c39c88fd3b0f5efed7d873bd2c0198a0a299.
We can now run the stack checker before migrations as per https://github.com/cloudfoundry/cloud_controller_ng/pull/3925.
This is an improvement as we want to fail the stack checker before any migrations have run so that we are not in a state where migrations have run but the deployment has failed

Revert "Run stack_check after DB migrations and seeds (#453)"

---

packages/nginx/packaging
packages/nginx/spec
packages/nginx_webdav/packaging
packages/nginx_webdav/spec

PCRE (Perl Compatible Regular Expressions) is part of the nginx packaging scripts.
We use an outdated version 8.45. The current version of pcre2 is 10.44.
Updating to newer version pcre2 10.44.

Update pcre 8.45 to newer pcre2 10.44

---

config/blobs.yml
packages/nginx/packaging
packages/nginx/spec
packages/nginx_webdav/packaging
packages/nginx_webdav/spec

This reverts commit ecc2b5d & ecc2b5d9dcb6c270fecb8e446d3acdd18e8580ef
pcre2 causes the following error when executing CATS:
```
Unknown field(s): '<ngx_upload_module_dummy>', Upload must include either resources or bits, File field missing path information
```

Revert "Update pcre 8.45 to newer pcre2 10.44 (#455)"

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_worker/spec

A simple solution for #458, however we should probably just remove the configuration of this property completely from the worker/clock specs.

Turn on audit logging in worker/clock by default

---

jobs/cc_deployment_updater/monit
jobs/cc_deployment_updater/spec
jobs/cloud_controller_clock/monit
jobs/cloud_controller_clock/spec
jobs/cloud_controller_ng/monit
jobs/cloud_controller_ng/spec
jobs/cloud_controller_worker/monit
jobs/cloud_controller_worker/spec

Add a new optional method to specify memory thresholds.This percent method allows for easier use of Puma where the VM size maybe scaled verticially, this method allows these thresholds to also scale.
Thin could only be scaled horizontally, Puma can be scaled vertically. Due to this the default memory in MB values may be insufficient for Puma installations on large VMs where there is more resource utilisation. Therefore instead of having to configure the MB threshold for the Puma installation based on the VM size, we add a percentage method that can be configured this allows the threshold to scales with the VM.

Add percent monit memory thresholds

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

[cloud_controller_ng/pull/3887](https://github.com/cloudfoundry/cloud_controller_ng/pull/3887) introduces the option run multiple delayed worker threads for one worker process. To allow operators to configure the number of threads a new config parameter is needed.
- Related to [cloud_controller_ng/pull/3887](https://github.com/cloudfoundry/cloud_controller_ng/pull/3887)

 Add threads parameter for delayed workers

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

Introduces `cc.jobs.queues.cc_generic.timeout_in_seconds` parameter which allows operators to configure a dedicated timeout for jobs in the cc-generic queue. 
Generic jobs are only enqueued on API VMs, thus the parameter is not needed for workers, clock etc.
Related to [ccng PR #3945](https://github.com/cloudfoundry/cloud_controller_ng/pull/3945).

Add timeout parameter for generic queue

---

jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

Ensure queues parameter is set to empty hash otherwise the schema validation might fail with nil errors.

Ensure queues parameter is set to empty hash

---

config/blobs.yml
packages/nginx/README.md
packages/nginx/packaging
packages/nginx/spec
packages/nginx_webdav/packaging
packages/nginx_webdav/spec

Update nginx from 1.25.2 to latest version 1.27.1.
Latest version comes with several bug fixes. Current version 1.25.2 is over a year old.

Update nginx to latest version 1.27.1

---

packages/cloud_controller_ng/packaging

One gem we install has a few world-writable files.
Thankfully, none of them are actually loaded while running CC, as far as I can tell, but this was flagged by a scanner as a potential security issue. 
See this issue for more info: https://github.com/rdp/os/issues/44.  It appears to have been unintentional, so if this can happen accidentally we'd like to prevent it in the future.

Ensure gems don't have world-writable files

---

jobs/cloud_controller_ng/spec

* STOPPING state could be a breaking change
related: https://github.com/cloudfoundry/cloud_controller_ng/pull/3984

Make STOPPING state optional

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb

Related cloud_controller_ng PR: cloudfoundry/cloud_controller_ng#3980
The default value (i.e. 90 days) equals the previously hard-coded interval.

Configurable pollable jobs cleanup

---

config/blobs.yml
packages/nginx/README.md
packages/nginx/packaging
packages/nginx/spec

This reverts the latest nginx update (commit 6c497f98faddd0adf261728b8eb37f2cf8479bd1). It causes errors like this:
```
Building a release from directory '/tmp/build/cc76e2d9/capi-release':
- Constructing packages from directory:
- Reading package from '/tmp/build/cc76e2d9/capi-release/packages/nginx_webdav':
Collecting package files:
Missing files for pattern 'nginx/nginx-1.27.1.tar.gz'
- Constructing jobs from manifest:
- Expected to find package 'nginx_webdav' since it's a dependency of job 'blobstore'
- Expected to find package 'capi_utils' since it's a dependency of job 'cc_deployment_updater'
- Expected to find package 'capi_utils' since it's a dependency of job 'cc_uploader'
- Expected to find package 'capi_utils' since it's a dependency of job 'cloud_controller_clock'
- Expected …
```

Revert "Bump nginx to 1.27.2"

---

jobs/cc_deployment_updater/templates/bin/cc_deployment_updater.erb
jobs/cloud_controller_clock/templates/bin/cloud_controller_clock.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/bin/cloud_controller_ng.erb
jobs/cloud_controller_ng/templates/bin/local_worker.erb
jobs/cloud_controller_ng/templates/bpm.yml.erb
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/templates/bin/cloud_controller_worker.erb
jobs/rotate_cc_database_key/templates/bin/run.erb
jobs/valkey/monit
spec/cloud_controller_ng/bpm_spec.rb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb
spec/valkey/monit_spec.rb

Make Puma the default webserver as it has been running on big foundations and brings performance boosts, better resource utilization and is well maintained. Thin can be still enabled by using the newly introduced config parameter `cc. temporary_enable_deprecated_thin_webserver `. `jemalloc` is now enabled globally for all CAPI jobs providing better memory management.
- Config `cc.experimental.use_puma_webserver` has been removed
- Config `cc.experimental.use_jemalloc_memory_allocator` has been removed
- Puma default config is 2 workers with each 10 threads and 10 DB connections

Make puma default webserver

---

jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/templates/nginx_external_endpoints.conf.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

Disable /v2/info endpoint if temporary_enable_v2 == false.
Part of the v2 deprecation story: https://github.com/cloudfoundry/community/pull/941
https://github.com/cloudfoundry/cloud_controller_ng/pull/4034

Disable /v2/info endpoint if temporary_enable_v2 == false

---

jobs/cc_deployment_updater/templates/bin/cc_deployment_updater.erb
jobs/cloud_controller_clock/templates/bin/cloud_controller_clock.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/bin/cloud_controller_ng.erb
jobs/cloud_controller_ng/templates/bin/local_worker.erb
jobs/cloud_controller_ng/templates/bpm.yml.erb
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/templates/bin/cloud_controller_worker.erb
jobs/rotate_cc_database_key/templates/bin/run.erb
jobs/valkey/monit
spec/cloud_controller_ng/bpm_spec.rb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb
spec/valkey/monit_spec.rb

This reverts commit 781690ed37e2add4ab264e3b268b59d53ca8dd69.
---
While we would like to see Puma be made the default web server, removing this property with no notice is problematic for us as we have non cf-d deployments that consume this property explicitly. Instead, perhaps for now these property defaults could be changed to `true` for a period of releases before being removed in its entirety.
We'd also like to workout a more formal deprecation policy for properties. Additionally, going forward, I think this pattern of including `experimental` in the name of the property only causes problems when we have to eventually remove them and replace them with something else. Perhaps we could have just had `enable_puma` as a property with a textual description stating it was experimental and …

Revert "Make puma default webserver (#481)"

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

Add `temporary_enable_v2` config flag to cc-worker configuration. Required for service broker client fix: https://github.com/cloudfoundry/cloud_controller_ng/pull/4058
Part of v2 deprecation story: https://github.com/cloudfoundry/community/pull/941
https://github.com/cloudfoundry/cloud_controller_ng/pull/4058
-> ran tests on new "gyro" env: https://concourse.app-runtime-interfaces.ci.cloudfoundry.org/teams/capi-team/pipelines/capi/jobs/gyro-exp-tests/builds/5
Test suite is basically green with this PR. The 4 failing tests must be fixed in CATs.

Add temporary_enable_v2 flag to cc-worker config

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

Add the config parameter "max_valid_packages_stored" to the "cloud_controller_worker" job.
This is needed for https://github.com/cloudfoundry/cloud_controller_ng/pull/4111.
https://github.com/cloudfoundry/cloud_controller_ng/pull/4116

Add "max_valid_packages_stored" config param to worker template

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb

Allows operators to provide a different sleep delay for the delayed workers. This can be used to e.g. reduce the database load of the delayed_jobs table.
Related to https://github.com/cloudfoundry/cloud_controller_ng/pull/4149

Explicitly configure worker sleep delay

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

This PR adds a config parameter and UAA client for shadow user creation described in https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0033-user-creation-by-org-managers.md
- Add UAA client to ccng
- Add `allow_user_creation_by_org_manager` config
PR in ccng: https://github.com/cloudfoundry/cloud_controller_ng/pull/4113

Add config for shadow user creation

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/drain.sh.erb
jobs/cloud_controller_ng/templates/shutdown_drain.rb.erb
spec/cloud_controller_ng/drain_spec.rb

**A short explanation of the proposed change:**
In case of a graceful shutdown of a CC api VM, local-worker will wait before shutdown if there are still jobs running on the local-worker queue. The default grace period is set to 5 minutes, it is configurable by setting a value for: ```cc.jobs.local.local_worker_grace_period_seconds```.   
The order of the shutdown is now:
- shutdown nginx
- shutdown cloud_controller
- shutdown local_worker
Before the order was shutdown local_worker, then nginx, then cloud_controller.  
**An explanation of the use cases your change solves:**
It seems that a graceful shutdown of a CC API VM (e.g., during an update) does not properly account for draining the worker jobs on the API VM that handle file uploads. 
When the CC API VM is restarted or recreated …

Draining CC-api VMs should let local-worker jobs finish

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

https://github.com/cloudfoundry/cloud_controller_ng/pull/4166

Allow configuring Puma to set worker count to number of detected cores

---

.gitignore
jobs/cloud_controller_ng/spec
spec/cloud_controller_ng/cloud_controller_ng_spec.rb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

Disable v2 by default. Can be re-enabled using `cc.temporary_enable_v2`
See [RFC0032 - CF API v2 End of Life](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0032-cfapiv2-eol.md) and https://github.com/cloudfoundry/community/issues/1001

Disable v2 by default

---

jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/templates/post-start.sh.erb
jobs/cloud_controller_worker/templates/pre-start.sh.erb
jobs/cloud_controller_worker/templates/prom_scraper_config.yml.erb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb
spec/cloud_controller_worker/prom_scraper_spec.rb

Add configuration for publishing metrics on cc-worker VMs
https://github.com/cloudfoundry/cloud_controller_ng/pull/4205

Add configuration for publishing cc-worker metrics

---

jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/prom_scraper_config.yml.erb
jobs/cloud_controller_worker/templates/scrape.crt.erb
jobs/cloud_controller_worker/templates/scrape.key.erb
jobs/cloud_controller_worker/templates/scrape_ca.crt.erb

Add certs and keys to enable mTLS communication between cc-worker metrics endpoint and scraper.
https://github.com/cloudfoundry/cloud_controller_ng/pull/4214

Add TLS certs and keys for cc-worker metrics endpoint

---

jobs/cloud_controller_worker/templates/prom_scraper_config.yml.erb

Add the label `origin: cc_worker` to prom_scraper config of cc-worker.

Add label 'origin: cc_worker' to cc-worker's prom_scraper config

---

jobs/cloud_controller_clock/spec
jobs/cloud_controller_clock/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/spec
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_clock/cloud_controller_clock_spec.rb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

The number of jobs to read ahead from the delayed job queue. Defaults to 5 for MySql and 0 for PostgreSQL (= use SELECT FOR UPDATE instead of read-ahead).
Allows lock_with_read_ahead for PostgreSQL to address a severe performance issue under heavy job load.
Using lock_with_for_update showed severe performance problems on postgres when there is a high number of jobs in the queue (>50k). Job processing starves due to row locks and temp IO gets high.
lock_with_read_ahead performs much better under such load situations.
Performance on low/normal job load is comparable.
See also cloudfoundry/cloud_controller_ng#4231

New config: cc.jobs.read_ahead

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

See #4306 and https://github.com/cloudfoundry/cloud_controller_ng/pull/4307

Add custom root links

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb

Adds config for enabling ipv6
CC: https://github.com/cloudfoundry/cloud_controller_ng/pull/4318
RFC: https://github.com/cloudfoundry/community/pull/1077

Add cc.enable_ipv6 to config

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb

The migration of primary keys from `int` to `bigint` (currently PostgreSQL only, starting with the **events** table) will not be performed when this flag is set to `true`. The default value is `false` meaning the multi-step migration will be started.
Related PR: https://github.com/cloudfoundry/cloud_controller_ng/pull/4281

Flag skip_bigint_id_migration

---

jobs/cc_uploader/monit
jobs/cloud_controller_ng/templates/shutdown_drain.rb.erb

This reverts commit 45d2a21fc5e4d71e3dcf971b006e5a6d2b2b94db.
This original commit introduces the requirement that cc_uploader is co-located on the same VM as the cloud_controller_ng job. While this is the case in cf-deployment, this is not the case for all deployments of CF (like the VMware one).
As this commit has broken our deployment, and its not easy for us simply to relocate the job, we propose we revert this and discuss options going forwards.
The cc_uploader originally was designed an independent process, typically processes that require to be co-located are within the same job. E.g. nginx, cloud_controller_ng and cloud_controller_local_worker.
Some options:
* Investigate a way to generically drain uploads from any source in nginx rather than specifically in cc_uploader.
* Current …

Revert "Add draining for cc_uploader (#529)"

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb
jobs/cloud_controller_worker/templates/cloud_controller_ng.yml.erb
spec/cloud_controller_ng/cloud_controller_ng_spec.rb
spec/cloud_controller_worker/cloud_controller_worker_spec.rb

Make default_app_lifecycle configurable

---

jobs/cloud_controller_ng/templates/bin/cloud_controller_ng.erb

We want to compare key labels configured in cloud_controller_ng.yml with those used in the different database tables ("encryption_key_label" row) and when a key label is used but not configured, simply fail to start. This validation step is only performed when cc.database_encryption.skip_validation is not set to true.
This change ensures that the Cloud Controller fails fast during startup if encryption keys referenced in the database are not properly configured. In environments where data encryption is enabled, having a mismatch between configured encryption keys and those in use can lead to runtime failures or silent decryption issues. 

Add validation of db encryption keys to cc_ng pre start migrations

---

jobs/cloud_controller_ng/spec
jobs/cloud_controller_ng/templates/ccng_monit_http_healthcheck.sh.erb
jobs/cloud_controller_ng/templates/nginx.conf.erb
spec/cloud_controller_ng/healthcheck_spec.rb
spec/cloud_controller_ng/nginx_spec.rb

Configure monit to use the new /internal/v4/status endpoint to determine whether CC is healthy and trigger restarts only when it returns unhealthy or 10 minutes have passed since the last OK was reported.
This change prevents restarts of CC, even it is still healthy and working off peak loads.
https://github.com/cloudfoundry/cloud_controller_ng/pull/4441

Configure new status health check
